### ISSUE TITLE
Revisit modules

### ISSUE THREAD

**Issue by bradbeam** [talos-systems/kernel#20]
When going with a static kernel, we run into significant issues with interoperability with other applications ( rook, kubelet, ceph, etc ). This has caused us to implement some hacky bits to work around these limitations, notably talos-systems/kernel#19  #11. 

We should figure out how we want to approach this for a long term approach
- update/patch modprobe to work against a static kernel
- start a convo with linux mail list(?)
- downgrade from an entirely static kernel to a signed module approach

**Comment by andrewrynhard** [comment]
I think we can close this, we already have PRs approved to move to signed kernel modules.
