### ISSUE TITLE
Enable BPF settings required by Cilium

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/kernel#22]
Required:

- `CONFIG_BPF_JIT`
- `CONFIG_NET_CLS_BPF`

Optional:

- `CONFIG_BPF_JIT`
- `CGROUP_BPF`
- `CONFIG_BPF_EVENTS`
- `CONFIG_BPF_SYSCALL`
- `CONFIG_HAVE_EBPF_JIT`

**Comment by Ulexus** [comment]
Technically, the complete required set is:  
  - `CONFIG_BPF=y`
  - `CONFIG_BPF_SYSCALL=y`
  - `CONFIG_NET_SCH_INGRESS=[m|y]`
  - `CONFIG_NET_CLS_BPF=[m|y]`
  - `CONFIG_NET_CLS_ACT=y`
  - `CONFIG_BPF_JIT=y`
  - `CONFIG_HAVE_EBPF_JIT=y`

The optional set is:
  - `CONFIG_CGROUP_BPF=y`
  - `CONFIG_LWTUNNEL_BPF=y`
  - `CONFIG_BPF_EVENTS=y`

Taken from [cilium/cilium:bpf/run_probes.sh](https://github.com/cilium/cilium/blob/master/bpf/run_probes.sh#L46)

**Comment by Ulexus** [comment]
One problem:  `CONFIG_BPF_JIT` _requires_ kernel modules to be enabled, which is currently not done.  It's easy enough to change this, but that leaves open to manual enforcement of a no-module policy.

Note that it doesn't need to be compiled _as_ a module; it just needs module support enabled.
