### ISSUE TITLE
Compile in required Azure kernel modules

### ISSUE THREAD

**Issue by bvierra** [talos-systems/kernel#24]
In order to support Azure the following config options need to be enabled:

CONFIG_HYPERV
CONFIG_HYPERV_NET
CONFIG_HYPERV_STORAGE
CONFIG_HYPERV_TSCPAGE

In the future the following option may need to be turned on as well for HPC instances as well as RDMA support (More info: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-hpc):

CONFIG_HYPERV_INFINIBAND_ND

If GPU support is needed as well you will need to install the CUDA drivers from intel and if RDMA is supported on that instance type the infiniband open above needs to be compiled in. More info: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup

Additional options that may be worth looking into adding in the future:

CONFIG_HYPERV_UTILS

The following were not enabled due to not being supported on Azure:

CONFIG_HYPERV_BALLOON
CONFIG_HYPERV_VSOCKETS

**Comment by andrewrynhard** [comment]
Closed by #25.
